---
apiVersion: objectbucket.io/v1alpha1
kind: PluginRegistration
metadata:
  name: example-pluginregistration
spec:
  pluginName: "example-plugin"
  host: "localhost:8080"
---
#kind: Secret
#apiVersion: v1
#metadata:
#  name: aws-creds
#stringData:
#  file: "file contents"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosi-plugin-s3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cosi-plugin-s3
  template:
    metadata:
      labels:
        name: cosi-plugin-s3
    spec:
      containers:
        - name: cosi-s3-plugin
          image: jcoperh/plugin
          imagePullPolicy: Never
          args:
            - "-alsologtostderr"
          env:
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: "/aws/credentials"
            - name: AWS_REGION
              value: "us-east-1"
            - name: COSI_CERT_PATH
              value: "/cosi/tls/tls.crt"
            - name: COSI_KEY_PATH
              value: "/cosi/tls/tls.key"
          volumeMounts:
            - mountPath: "/cosi/aws/"
              name: aws-creds
            - mountPath: "/cosi/tls/"
              name: tls
          envFrom:
            - secretRef:
                name: example-pluginregistration
      volumes:
        # Generate this secret via
        # $ kubectl create secret generic aws-creds --from-file=<path to /.aws/credentials>
        - name: aws-creds
          secret:
            secretName: aws-creds
        - name: tls
          secret:
              secretName: example-pluginregistration